<?php



/**
 * Skeleton subclass for representing a row from the 'system_event_instance_message' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.0 on:
 *
 * Mon Jul 18 12:23:28 2011
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class SystemEventInstanceMessage extends BaseSystemEventInstanceMessage {

} // SystemEventInstanceMessage
