// This file was autogenerated by /home/ssperandeo/dev/homer6/blog_altumo/htdocs/project/plugins/sfAltumoPlugin/lib/vendor/altumo/lib/javascript/vendor/google/closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('/../../../../../../../../../altumo/js/src/api/AltumoApiClient.js', ['altumo.api', 'altumo.api.AltumoApiClient'], []);
goog.addDependency('/../../../../../../../../../altumo/js/src/configuration/Config.js', ['altumo.configuration.Config'], []);
goog.addDependency('/../../../../../../../../../altumo/js/src/core/Altumo.js', ['altumo.core.Altumo'], ['altumo.configuration.Config', 'altumo.routing.Router']);
goog.addDependency('/../../../../../../../../../altumo/js/src/routing/Router.js', ['altumo.routing.Router'], []);
