// This file was autogenerated by /work/altumo/altumo.com/htdocs/project/plugins/sfAltumoPlugin/lib/vendor/altumo/lib/javascript/vendor/google/closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('/../../../../../../../../../altumo/js/src/api/AltumoApiClient.js', ['altumo.api', 'altumo.api.AltumoApiClient'], []);
goog.addDependency('/../../../../../../../../../altumo/js/src/app/Application.js', ['altumo.app.Application'], []);
goog.addDependency('/../../../../../../../../../altumo/js/src/behaviour/InputWatermark.js', ['altumo.behaviour.InputWatermark'], []);
goog.addDependency('/../../../../../../../../../altumo/js/src/model/Collection.js', ['altumo.model.Collection'], []);
goog.addDependency('/../../../../../../../../../altumo/js/src/model/Model.js', ['altumo.model.Model'], []);
goog.addDependency('/../../../../../../../../../altumo/js/src/router/Router.js', ['altumo.router.Router'], []);
goog.addDependency('/../../../../../../../../../altumo/js/src/view/SectionalApplicationView.js', ['altumo.view.SectionalApplicationView'], ['altumo.view.View']);
goog.addDependency('/../../../../../../../../../altumo/js/src/view/View.js', ['altumo.view.View'], []);
